setlocal omnifunc=javascriptcomplete#CompleteJS
setlocal autoindent
setlocal expandtab
setlocal smarttab
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
setlocal cindent
setlocal iskeyword+=$
