#!/bin/sh

# Bail on unitialized values
set -u
# Bail on errors
set -e

mkdir ~/src
for f in gvimrc inputrc rvmrc tmux.conf vim_colors vimrc pentadactylrc ackrc
do
    # echo line for debugging only
    echo ln -s "$HOME/src/dotfiles/${f}" "$HOME/.${f}"
    ln -s "$HOME/src/dotfiles/${f}" "$HOME/.${f}"
done

