#!/bin/sh
# Switch back to system Ruby/Python before updating
CURRENT_RUBY=$(rbenv version | head -n1 | cut -f1 -d' ')
CURRENT_PYTHON=$(pyenv version | head -n1 | cut -f1 -d' ')
CURRENT_NODE=$(nodenv version | head -n1 | cut -f1 -d' ')
echo "*** Active versions [Python: ${CURRENT_PYTHON} / Ruby: ${CURRENT_RUBY} / Node: ${CURRENT_NODE}] ***"
pyenv global 3.5.2
rbenv global system
# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
echo "*** System software"
echo
sudo softwareupdate -i -a
echo "*** App Store programs"
echo
sudo mas outdated
sudo mas upgrade
echo "*** Homebrew"
echo
brew doctor
brew update
brew upgrade
brew cleanup
brew prune
echo "*** npm"
echo
npm set progress=false
npm install -g npm@latest
for package in $(npm -g outdated --parseable --depth=0 | cut -d: -f2)
do
    npm -g install "$package"
done
echo "*** Ruby gems"
echo
sudo gem update --system
sudo gem update
echo "*** Vim bundles"
echo
TERM=xterm-256color vim -u ~/src/dotfiles/bundles.vim +PlugUpdate! +qa
echo "*** zprezto submodules"
echo
cd ~/src/zprezto || exit
git submodule update
git submodule foreach git pull origin master --recurse-submodules
echo
echo "Restoring previous Python/Ruby/Node versions"
pyenv global "${CURRENT_PYTHON}"
rbenv global "${CURRENT_RUBY}"
nodenv global "${CURRENT_NODE}"
