#!/bin/sh
# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
echo "*** System software"
echo
sudo softwareupdate -i -a
echo "*** Homebrew"
echo
brew doctor
brew update
brew upgrade --all
brew cleanup
echo "*** npm"
echo
npm install -g npm@latest
for package in $(npm -g outdated --parseable --depth=0 | cut -d: -f2)
do
    npm -g install "$package"
done
echo "*** Ruby gems"
echo
sudo gem update --system
sudo gem update
echo "*** Vim bundles"
echo
TERM=xterm-256color vim -u ~/src/dotfiles/bundles.vim +PlugUpdate! +qa
echo "*** zprezto submodules"
echo
cd ~/src/zprezto || exit
git submodule update
git submodule foreach git pull origin master --recurse-submodules
echo
echo "*** Docker ***"
echo "NOT running 'boot2docker upgrade'"
